SELECT
    c."C_NAME",
    c."C_MKTSEGMENT",
    SUM(l."L_EXTENDEDPRICE" * (1 - l."L_DISCOUNT")) AS "revenue"
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" AS c
JOIN "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS" AS o
    ON o."O_CUSTKEY" = c."C_CUSTKEY"
JOIN "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."LINEITEM" AS l
    ON l."L_ORDERKEY" = o."O_ORDERKEY"
WHERE o."O_ORDERDATE" >= '1995-01-01'
  AND o."O_ORDERDATE" < '1995-04-01'
  AND l."L_RETURNFLAG" = 'R'
GROUP BY c."C_NAME", c."C_MKTSEGMENT"
ORDER BY "revenue" DESC
LIMIT 10;
